
#define PIN_BATTERY_VOLTAGE A1

#define PIN_BRIGHTNESS_SENSOR A5


#define PIN_LED_PUMP_STATE 2
#define PIN_LED_BATT_STATE 3
#define PIN_LED_MOTOR_STATE 4

#define PIN_RELAIS_BATT_AC 2
#define PIN_RELAIS_MOTOR_ON 6
#define PIN_RELAIS_MOTOR_UP 7
#define PIN_RELAIS_MOTOR_DOWN 8
#define PIN_RELAIS_PUMP 9

#define PIN_DISPLAY_DIN 10
#define PIN_DISPLAY_CS 11
#define PIN_DISPLAY_CLK 12

#define PIN_BUTTON 13
