
#define PIN_SENSOR_EAST A4
#define PIN_SENSOR_WEST A5

#define PIN_LED_MOTOR_STATE 4
#define PIN_LED_PUMP_STATE 5

#define PIN_RELAIS_MOTOR_ON 6
#define PIN_RELAIS_MOTOR_UP 7
#define PIN_RELAIS_MOTOR_DOWN 8
#define PIN_RELAIS_PUMP 9
